### ISSUE TITLE
Main TODO list

### ISSUE THREAD

**Issue by RaidAndFade** [RaidAndFade/Haxicord#4]
Completion / Feature list (for my own sake)

--- 
Websocket :
- [x] Connect and Identify
- [x] Heartbeat
- [x] Ready
- [x] Bootleg resume (Reconnect on disconnect)
- [x] Resume
- [x] Handle events
---
REST
- [x] requests implemented with headers and proper POST/GET data
- [x] request proper error handling (returns in callback rather than throwing in request)
- [x] Burst ratelimiting methods to make sure 429s do not happen
- [x] Global ratelimit watch/handler
- [x] Implement every single documented v5 route
- [x] Document every single v5 route. Document permissions required as well
- [x] Document every typedef used for the routes.
- [x] Find audit log and impl
---
Working Targets : 
- [x] Neko
- [ ] CPP
- [x] C#
- [x] NodeJS
- [ ] PHP
- [ ] Java
- [ ] Python
- [ ] Browser JS (probably not happening, considering Browsers cant set useragents)
- [ ] Lua

**Comment by RaidAndFade** [comment]
All of the library features required in this list are completed. This is completed and closed, targets will be added as requested over time.
